format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/tm70/kr4383/access-esm/archive/esm-historical/restart001/atmosphere/restart_dump.astart
  hashes:
    binhash: af47637e66864f1e60d5e08f3736c9b4
    md5: b5738c7f1c692d0d6c42678fb9642ac6
work/atmosphere/um.res.yaml:
  fullpath: /scratch/tm70/kr4383/access-esm/archive/esm-historical/restart001/atmosphere/um.res.yaml
  hashes:
    binhash: 4919972b204ed7db2858ef8d1e3e56ae
    md5: acec8afe6fb93e1400de362f2c16c156
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/tm70/kr4383/access-esm/archive/esm-historical/restart001/coupler/a2i.nc
  hashes:
    binhash: fd1d4a5c744a28129b777c13931190f5
    md5: 4330240165678611f4eaf60a39e40f73
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/tm70/kr4383/access-esm/archive/esm-historical/restart001/coupler/i2a.nc
  hashes:
    binhash: 14dfc8cc8abf005597cbb63b306bff6a
    md5: aeb74525567aced6e03790bd983167d8
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/tm70/kr4383/access-esm/archive/esm-historical/restart001/coupler/o2i.nc
  hashes:
    binhash: 4f07def55a0441cfec51274746494eb0
    md5: c19f8333be9a71b9181193dfd2774ac7
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/tm70/kr4383/access-esm/archive/esm-historical/restart001/ice/cice_in.nml
  hashes:
    binhash: 04689bd6c91c3fdef39712e2846b2a8e
    md5: a0c9349e3495c05bd39ecff72f733e4c
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/tm70/kr4383/access-esm/archive/esm-historical/restart001/ice/ice.restart_file
  hashes:
    binhash: 296ad7f713f5fea3a63cb0a0c2d01057
    md5: 32ac43bc3aa3b99f371a3189726c85c4
work/ice/RESTART/iced.18500201:
  copy: true
  fullpath: /scratch/tm70/kr4383/access-esm/archive/esm-historical/restart001/ice/iced.18500201
  hashes:
    binhash: 7acefec49f8cf045ab2924ba42ef44fc
    md5: 019eb6e4524a236979c8eacb3426e6c4
work/ice/RESTART/input_ice.nml:
  copy: true
  fullpath: /scratch/tm70/kr4383/access-esm/archive/esm-historical/restart001/ice/input_ice.nml
  hashes:
    binhash: 2bf7d1f92606a43e27849f00167fc827
    md5: dedeb603fdbd8549e0c39db8bbc29eb5
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/tm70/kr4383/access-esm/archive/esm-historical/restart001/ice/mice.nc
  hashes:
    binhash: bce68a171024cfaaec82ff4535560fb7
    md5: d2c3d3fa6ce9842b4f92c54523506066
work/ocean/INPUT/csiro_bgc.res.nc:
  fullpath: /scratch/tm70/kr4383/access-esm/archive/esm-historical/restart001/ocean/csiro_bgc.res.nc
  hashes:
    binhash: 4a2d93cae44c41b0289007fc7f478646
    md5: 2c5af158bfdc15ad30b206077783f94a
work/ocean/INPUT/csiro_bgc_sediment.res.nc:
  fullpath: /scratch/tm70/kr4383/access-esm/archive/esm-historical/restart001/ocean/csiro_bgc_sediment.res.nc
  hashes:
    binhash: 331bdffc38bfe2a0bcb498938eb70771
    md5: 8401da385dd12c834bf303f4bbe4e50f
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/tm70/kr4383/access-esm/archive/esm-historical/restart001/ocean/ocean_age.res.nc
  hashes:
    binhash: 9a5c4707db66a04d44e1ac603cbc758e
    md5: 139425e10784ea512c4fa4038e479696
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/tm70/kr4383/access-esm/archive/esm-historical/restart001/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 1eb6946d43288056a9bf5ebb64448f17
    md5: c60c9bbf37b2158bdddfc9ba80cb70a5
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/tm70/kr4383/access-esm/archive/esm-historical/restart001/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 46866c3c0108123d0c0cb097c95321d3
    md5: da27212b2fed80c3b2cd363e39c009f6
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/tm70/kr4383/access-esm/archive/esm-historical/restart001/ocean/ocean_density.res.nc
  hashes:
    binhash: cae285c6141b605874877a4b436e1e2d
    md5: d74295789070b38566687bb8e8b491d4
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/tm70/kr4383/access-esm/archive/esm-historical/restart001/ocean/ocean_frazil.res.nc
  hashes:
    binhash: ed348c4ee4f2ca4dd358a3a91d110b42
    md5: a9fe8a2b11f96517f3aa4682ad626c7b
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/tm70/kr4383/access-esm/archive/esm-historical/restart001/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 4767a4d17c52e693c6a5396406f70060
    md5: 5d59b3ee57d322c44d376009e3c76be0
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/tm70/kr4383/access-esm/archive/esm-historical/restart001/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 7d524250e0b236c282657e22565ca7e8
    md5: c3253cc0f13da15a06b9ea6f8f981482
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/tm70/kr4383/access-esm/archive/esm-historical/restart001/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 2f241e5aced57bd786f0156f99280d4f
    md5: 23f55128ae365884864c7e00cf88eace
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/tm70/kr4383/access-esm/archive/esm-historical/restart001/ocean/ocean_sbc.res.nc
  hashes:
    binhash: cdc1a188978a50c8b82ce2ebeb5e2c2f
    md5: a11172e9f128128f80faae1507742aa3
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/tm70/kr4383/access-esm/archive/esm-historical/restart001/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 0682a6ef879c1b201d66d4508605d0b8
    md5: fe527a9917d30955d0dc082271c1392f
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/tm70/kr4383/access-esm/archive/esm-historical/restart001/ocean/ocean_solo.res
  hashes:
    binhash: abfb64be6a7cf77611012626d98f80f7
    md5: 6fff72f8951b1b2ce65573edadbc7a9c
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/tm70/kr4383/access-esm/archive/esm-historical/restart001/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 50acf8a01f1ac042cad204db4ad72858
    md5: 9e5ad374e23ca862f998a2780f0f1819
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/tm70/kr4383/access-esm/archive/esm-historical/restart001/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 0295241740db48b6ff1da87f77bc5180
    md5: 6e94877d9a5cf908dd486d9e422c9174
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/tm70/kr4383/access-esm/archive/esm-historical/restart001/ocean/ocean_tracer.res
  hashes:
    binhash: ae084200e01d0bc7b1b4395ff818f704
    md5: e4964c94027cd662ae365e5e25ec57c3
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/tm70/kr4383/access-esm/archive/esm-historical/restart001/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 7075211ec8f4544a0388c9b123202cce
    md5: 1b42529b2f3b2c8356aa25838002c7d3
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/tm70/kr4383/access-esm/archive/esm-historical/restart001/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: b6acb34f94886fe5cf722a1c45d0ae3f
    md5: f6e5744229642fd1be3b9c991c30ad7d
