format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/tm70/kr4383/access-esm/archive/esm-historical/restart000/atmosphere/restart_dump.astart
  hashes:
    binhash: 5bc27e2ff44651ae8cbacefd0c259f82
    md5: c46e4c9265692579cdca359972bfd3d4
work/atmosphere/um.res.yaml:
  fullpath: /scratch/tm70/kr4383/access-esm/archive/esm-historical/restart000/atmosphere/um.res.yaml
  hashes:
    binhash: f64cbb5f967674e32ae0ae27431c5b9b
    md5: 78f26c60a2e2e0336c7acec9bfecd7bf
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/tm70/kr4383/access-esm/archive/esm-historical/restart000/coupler/a2i.nc
  hashes:
    binhash: 4b1072d5eb661fb9e6b0f6e1aae6016e
    md5: 53c917f70f867e37a084672e8a1997db
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/tm70/kr4383/access-esm/archive/esm-historical/restart000/coupler/i2a.nc
  hashes:
    binhash: f8efe36058a1ba202922314b5cba6f2e
    md5: a30b12d2709ef6ae6bb40444b1db0ee2
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/tm70/kr4383/access-esm/archive/esm-historical/restart000/coupler/o2i.nc
  hashes:
    binhash: 6a47219117a85cde7f66be5d6d46e40a
    md5: 66a4bed2d785d04bf9041e14eb15d87f
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/tm70/kr4383/access-esm/archive/esm-historical/restart000/ice/cice_in.nml
  hashes:
    binhash: f7f3094874a95b712686f777f305702e
    md5: 1576287c82da88ffc4752430100f848e
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/tm70/kr4383/access-esm/archive/esm-historical/restart000/ice/ice.restart_file
  hashes:
    binhash: 5fee78d296b2c11f95f8dc5ced3fee06
    md5: 507c36763937f8f47d5a592c5d24095d
work/ice/RESTART/iced.18500101:
  copy: true
  fullpath: /scratch/tm70/kr4383/access-esm/archive/esm-historical/restart000/ice/iced.18500101
  hashes:
    binhash: c4b9b914ce90ad1a169846c36e486e2d
    md5: ca0d4395cfadb19a9b0ab4d07bd25961
work/ice/RESTART/input_ice.nml:
  copy: true
  fullpath: /scratch/tm70/kr4383/access-esm/archive/esm-historical/restart000/ice/input_ice.nml
  hashes:
    binhash: eef8577c0d03c77b49f78b55a992dfae
    md5: 48d62b9cbf71fe6373c02005adb58471
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/tm70/kr4383/access-esm/archive/esm-historical/restart000/ice/mice.nc
  hashes:
    binhash: ea677264707314b10dbd8786f211163b
    md5: 08bd0706328be256d82a22b21a972f6b
work/ocean/INPUT/csiro_bgc.res.nc:
  fullpath: /scratch/tm70/kr4383/access-esm/archive/esm-historical/restart000/ocean/csiro_bgc.res.nc
  hashes:
    binhash: d4727e2a5d671675595e51b470c09d7a
    md5: 0567fdf6be0e1f7da67e3f7aed3e32c0
work/ocean/INPUT/csiro_bgc_sediment.res.nc:
  fullpath: /scratch/tm70/kr4383/access-esm/archive/esm-historical/restart000/ocean/csiro_bgc_sediment.res.nc
  hashes:
    binhash: c7a13c11bc445ded1ef3a6f6338af041
    md5: d1de12ab9eef3a4ba17113a801f9e6f8
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/tm70/kr4383/access-esm/archive/esm-historical/restart000/ocean/ocean_age.res.nc
  hashes:
    binhash: 1ff59fe2790d0cc03d0dcff2f278d076
    md5: b324bd43e343d2b8eb3bd5d9014e1dba
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/tm70/kr4383/access-esm/archive/esm-historical/restart000/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 21bf13726d52e4f276994e2424ee6416
    md5: 2c65c22e627689dbb99c7e48d198eec6
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/tm70/kr4383/access-esm/archive/esm-historical/restart000/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 5b6c84e1219cceff0dc85533078cb63d
    md5: 6cc40c8d7895bc9bf8d14066e5aa1fbd
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/tm70/kr4383/access-esm/archive/esm-historical/restart000/ocean/ocean_density.res.nc
  hashes:
    binhash: ba53b4395c957525750b41abb5ee6748
    md5: 07cdb0236d303b767ee6fb75ced59785
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/tm70/kr4383/access-esm/archive/esm-historical/restart000/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 63dd7ba184218920ff387c7a53b6550d
    md5: b6feb3d546146172f7d877f259f412a6
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/tm70/kr4383/access-esm/archive/esm-historical/restart000/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 05a5a4352f4178206604c46fd0b089f0
    md5: d2c9747a6a51b6edc4e7474b5e424bb3
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/tm70/kr4383/access-esm/archive/esm-historical/restart000/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 1494444cc73e8abdb716c1c306744b7a
    md5: ada60736c5cda5f230e0e57cc074f08b
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/tm70/kr4383/access-esm/archive/esm-historical/restart000/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: cea1a3d394f97bd81cea4edf14d01d86
    md5: f4f55e359da62c16c93bc2b394eb57e1
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/tm70/kr4383/access-esm/archive/esm-historical/restart000/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 74092dcaeb14a180751f8c36cd1a4abf
    md5: 329c77b819420ef9f878fef98818b9bf
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/tm70/kr4383/access-esm/archive/esm-historical/restart000/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 0cc151c9d928c0157d7ced9923bee698
    md5: fe527a9917d30955d0dc082271c1392f
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/tm70/kr4383/access-esm/archive/esm-historical/restart000/ocean/ocean_solo.res
  hashes:
    binhash: 4f7a08b5b6cd15a3ad6b3dc6ffa47c94
    md5: 2b1c789b3ff6389a05a769a0d0934334
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/tm70/kr4383/access-esm/archive/esm-historical/restart000/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: fb9b7e8b4db5f624bc917f28166cc9be
    md5: d59017739edb08299afe542567f73095
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/tm70/kr4383/access-esm/archive/esm-historical/restart000/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 03df675abe6f718f3a43338e9e3cea2b
    md5: 67be2b864dcb5e643aa2b80ae44e78ca
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/tm70/kr4383/access-esm/archive/esm-historical/restart000/ocean/ocean_tracer.res
  hashes:
    binhash: 0471ade11d281cea317d7cc5cc0c593b
    md5: 4d105dfe1fba502278db9e80d5ec1dae
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/tm70/kr4383/access-esm/archive/esm-historical/restart000/ocean/ocean_velocity.res.nc
  hashes:
    binhash: eecdcfacb1d48bc8af5c91aecd727241
    md5: bc927019d11866a8ae67cb5bd5ddec93
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/tm70/kr4383/access-esm/archive/esm-historical/restart000/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 3db964c49168a0be407b87eb3e00490a
    md5: 2183be2ef353d129f56688247b0fbf3d
